In [2]:
import sys
import os
import pandas as pd
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(project_root)

print(project_root)  # para verificar

c:\Users\marco\OneDrive\Escritorio\Mis_proyectitos\electricity-price-forecast

In [3]:
from src.scraper import download_omie_price

In [4]:
from src.scraper import download_omie_range_v2

In [21]:
df = download_omie_range_v2('20230101','20231231')

20230101: 7 columnas
      0    1    2    3    4    5   6
0  2023  1.0  1.0  1.0  0.0  0.0 NaN
1  2023  1.0  1.0  2.0  0.0  0.0 NaN
OK: 20230101 (24 horas)
20230102: 7 columnas
      0    1    2    3      4      5   6
0  2023  1.0  2.0  1.0  61.38  61.38 NaN
1  2023  1.0  2.0  2.0  42.17  42.17 NaN
OK: 20230102 (24 horas)
20230103: 7 columnas
      0    1    2    3       4       5   6
0  2023  1.0  3.0  1.0  130.01  130.01 NaN
1  2023  1.0  3.0  2.0  120.00  120.00 NaN
OK: 20230103 (24 horas)
20230104: 7 columnas
      0    1    2    3       4       5   6
0  2023  1.0  4.0  1.0  119.99  119.99 NaN
1  2023  1.0  4.0  2.0  100.00  100.00 NaN
OK: 20230104 (24 horas)
20230105: 7 columnas
      0    1    2    3      4      5   6
0  2023  1.0  5.0  1.0  95.05  95.05 NaN
1  2023  1.0  5.0  2.0  79.21  79.21 NaN
OK: 20230105 (24 horas)
20230106: 7 columnas
      0    1    2    3       4       5   6
0  2023  1.0  6.0  1.0  107.21  107.21 NaN
1  2023  1.0  6.0  2.0  101.10  101.10 NaN
OK: 20230106 (24 horas)
20230107: 7 columnas
      0    1    2    3      4      5   6
0  2023  1.0  7.0  1.0  53.42  53.42 NaN
1  2023  1.0  7.0  2.0  40.30  40.30 NaN
OK: 20230107 (24 horas)
20230108: 7 columnas
      0    1    2    3    4    5   6
0  2023  1.0  8.0  1.0  7.0  7.0 NaN
1  2023  1.0  8.0  2.0  5.0  5.0 NaN
OK: 20230108 (24 horas)
20230109: 7 columnas
      0    1    2    3    4    5   6
0  2023  1.0  9.0  1.0  5.1  5.1 NaN
1  2023  1.0  9.0  2.0  4.2  4.2 NaN
OK: 20230109 (24 horas)
20230110: 7 columnas
      0    1     2    3       4       5   6
0  2023  1.0  10.0  1.0  105.98  105.98 NaN
1  2023  1.0  10.0  2.0   96.79   96.79 NaN
OK: 20230110 (24 horas)
20230111: 7 columnas
      0    1     2    3     4     5   6
0  2023  1.0  11.0  1.0  35.0  35.0 NaN
1  2023  1.0  11.0  2.0   8.0   8.0 NaN
OK: 20230111 (24 horas)
20230112: 7 columnas
      0    1     2    3     4     5   6
0  2023  1.0  12.0  1.0  69.5  69.5 NaN
1  2023  1.0  12.0  2.0  56.6  56.6 NaN
OK: 20230112 (24 horas)
20230113: 7 columnas
      0    1     2    3      4      5   6
0  2023  1.0  13.0  1.0  59.83  59.83 NaN
1  2023  1.0  13.0  2.0  44.20  44.20 NaN
OK: 20230113 (24 horas)
20230114: 7 columnas
      0    1     2    3     4     5   6
0  2023  1.0  14.0  1.0  80.0  80.0 NaN
1  2023  1.0  14.0  2.0  73.5  73.5 NaN
OK: 20230114 (24 horas)
20230115: 7 columnas
      0    1     2    3      4      5   6
0  2023  1.0  15.0  1.0  25.00  25.00 NaN
1  2023  1.0  15.0  2.0  17.08  17.08 NaN
OK: 20230115 (24 horas)
20230116: 7 columnas
      0    1     2    3     4     5   6
0  2023  1.0  16.0  1.0  4.16  4.16 NaN
1  2023  1.0  16.0  2.0  3.00  3.00 NaN
OK: 20230116 (24 horas)
20230117: 7 columnas
      0    1     2    3     4     5   6
0  2023  1.0  17.0  1.0  4.16  4.16 NaN
1  2023  1.0  17.0  2.0  4.16  4.16 NaN
OK: 20230117 (24 horas)
20230118: 7 columnas
      0    1     2    3     4     5   6
0  2023  1.0  18.0  1.0  3.80  3.80 NaN
1  2023  1.0  18.0  2.0  0.57  0.57 NaN
OK: 20230118 (24 horas)
20230119: 7 columnas
      0    1     2    3      4      5   6
0  2023  1.0  19.0  1.0  40.86  40.86 NaN
1  2023  1.0  19.0  2.0  29.99  29.99 NaN
OK: 20230119 (24 horas)
20230120: 7 columnas
      0    1     2    3     4     5   6
0  2023  1.0  20.0  1.0  48.9  48.9 NaN
1  2023  1.0  20.0  2.0  44.5  44.5 NaN
OK: 20230120 (24 horas)
20230121: 7 columnas
      0    1     2    3      4      5   6
0  2023  1.0  21.0  1.0  75.76  75.76 NaN
1  2023  1.0  21.0  2.0  60.50  60.50 NaN
OK: 20230121 (24 horas)
20230122: 7 columnas
      0    1     2    3      4      5   6
0  2023  1.0  22.0  1.0  32.37  32.37 NaN
1  2023  1.0  22.0  2.0  18.00  18.00 NaN
OK: 20230122 (24 horas)
20230123: 7 columnas
      0    1     2    3      4      5   6
0  2023  1.0  23.0  1.0  50.00  50.00 NaN
1  2023  1.0  23.0  2.0  39.58  39.58 NaN
OK: 20230123 (24 horas)
20230124: 7 columnas
      0    1     2    3     4     5   6
0  2023  1.0  24.0  1.0  63.0  63.0 NaN
1  2023  1.0  24.0  2.0  51.9  51.9 NaN
OK: 20230124 (24 horas)
20230125: 7 columnas
      0    1     2    3      4       5   6
0  2023  1.0  25.0  1.0  98.86  100.00 NaN
1  2023  1.0  25.0  2.0  84.87   84.87 NaN
OK: 20230125 (24 horas)
20230126: 7 columnas
      0    1     2    3      4      5   6
0  2023  1.0  26.0  1.0  70.78  70.78 NaN
1  2023  1.0  26.0  2.0  60.60  60.60 NaN
OK: 20230126 (24 horas)
20230127: 7 columnas
      0    1     2    3     4     5   6
0  2023  1.0  27.0  1.0  48.8  48.8 NaN
1  2023  1.0  27.0  2.0  48.0  48.0 NaN
OK: 20230127 (24 horas)
20230128: 7 columnas
      0    1     2    3      4      5   6
0  2023  1.0  28.0  1.0  40.00  40.00 NaN
1  2023  1.0  28.0  2.0  36.69  36.69 NaN
OK: 20230128 (24 horas)
20230129: 7 columnas
      0    1     2    3      4      5   6
0  2023  1.0  29.0  1.0  52.34  52.34 NaN
1  2023  1.0  29.0  2.0  40.00  40.00 NaN
OK: 20230129 (24 horas)
20230130: 7 columnas
      0    1     2    3       4       5   6
0  2023  1.0  30.0  1.0  117.05  117.05 NaN
1  2023  1.0  30.0  2.0  119.60  119.60 NaN
OK: 20230130 (24 horas)
20230131: 7 columnas
      0    1     2    3       4       5   6
0  2023  1.0  31.0  1.0  125.28  125.28 NaN
1  2023  1.0  31.0  2.0  108.45  108.45 NaN
OK: 20230131 (24 horas)
20230201: 7 columnas
      0    1    2    3       4       5   6
0  2023  2.0  1.0  1.0  133.65  133.65 NaN
1  2023  2.0  1.0  2.0  121.51  121.51 NaN
OK: 20230201 (24 horas)
20230202: 7 columnas
      0    1    2    3       4       5   6
0  2023  2.0  2.0  1.0  119.89  119.89 NaN
1  2023  2.0  2.0  2.0  123.13  123.13 NaN
OK: 20230202 (24 horas)
20230203: 7 columnas
      0    1    2    3       4       5   6
0  2023  2.0  3.0  1.0  125.86  125.86 NaN
1  2023  2.0  3.0  2.0  124.48  124.48 NaN
OK: 20230203 (24 horas)
20230204: 7 columnas
      0    1    2    3       4       5   6
0  2023  2.0  4.0  1.0  158.09  158.09 NaN
1  2023  2.0  4.0  2.0  151.60  151.60 NaN
OK: 20230204 (24 horas)
20230205: 7 columnas
      0    1    2    3       4       5   6
0  2023  2.0  5.0  1.0  103.84  103.84 NaN
1  2023  2.0  5.0  2.0   94.02   94.02 NaN
OK: 20230205 (24 horas)
20230206: 7 columnas
      0    1    2    3      4      5   6
0  2023  2.0  6.0  1.0  105.0  105.0 NaN
1  2023  2.0  6.0  2.0   89.9   89.9 NaN
OK: 20230206 (24 horas)
20230207: 7 columnas
      0    1    2    3       4       5   6
0  2023  2.0  7.0  1.0  136.83  136.83 NaN
1  2023  2.0  7.0  2.0  131.76  131.76 NaN
OK: 20230207 (24 horas)
20230208: 7 columnas
      0    1    2    3       4       5   6
0  2023  2.0  8.0  1.0  137.55  137.55 NaN
1  2023  2.0  8.0  2.0  115.05  115.05 NaN
OK: 20230208 (24 horas)
20230209: 7 columnas
      0    1    2    3       4       5   6
0  2023  2.0  9.0  1.0  145.51  145.51 NaN
1  2023  2.0  9.0  2.0  142.47  142.47 NaN
OK: 20230209 (24 horas)
20230210: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  10.0  1.0  141.75  141.75 NaN
1  2023  2.0  10.0  2.0  140.88  140.88 NaN
OK: 20230210 (24 horas)
20230211: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  11.0  1.0  139.44  139.44 NaN
1  2023  2.0  11.0  2.0  135.86  135.86 NaN
OK: 20230211 (24 horas)
20230212: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  12.0  1.0  140.48  140.48 NaN
1  2023  2.0  12.0  2.0  134.47  134.47 NaN
OK: 20230212 (24 horas)
20230213: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  13.0  1.0  140.09  140.09 NaN
1  2023  2.0  13.0  2.0  138.76  138.76 NaN
OK: 20230213 (24 horas)
20230214: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  14.0  1.0  135.62  135.62 NaN
1  2023  2.0  14.0  2.0  132.32  132.32 NaN
OK: 20230214 (24 horas)
20230215: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  15.0  1.0  130.00  130.00 NaN
1  2023  2.0  15.0  2.0  126.11  126.11 NaN
OK: 20230215 (24 horas)
20230216: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  16.0  1.0  150.87  150.87 NaN
1  2023  2.0  16.0  2.0  145.95  145.95 NaN
OK: 20230216 (24 horas)
20230217: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  17.0  1.0  120.00  120.00 NaN
1  2023  2.0  17.0  2.0  114.16  114.16 NaN
OK: 20230217 (24 horas)
20230218: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  18.0  1.0  146.52  146.52 NaN
1  2023  2.0  18.0  2.0  134.06  134.06 NaN
OK: 20230218 (24 horas)
20230219: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  19.0  1.0  140.01  140.01 NaN
1  2023  2.0  19.0  2.0  117.54  117.54 NaN
OK: 20230219 (24 horas)
20230220: 7 columnas
      0    1     2    3      4      5   6
0  2023  2.0  20.0  1.0  111.5  111.5 NaN
1  2023  2.0  20.0  2.0  113.3  113.3 NaN
OK: 20230220 (24 horas)
20230221: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  21.0  1.0  149.35  149.35 NaN
1  2023  2.0  21.0  2.0  145.51  145.51 NaN
OK: 20230221 (24 horas)
20230222: 7 columnas
      0    1     2    3      4      5   6
0  2023  2.0  22.0  1.0  139.9  139.9 NaN
1  2023  2.0  22.0  2.0  128.0  128.0 NaN
OK: 20230222 (24 horas)
20230223: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  23.0  1.0  135.01  135.01 NaN
1  2023  2.0  23.0  2.0  131.77  131.77 NaN
OK: 20230223 (24 horas)
20230224: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  24.0  1.0  133.84  133.84 NaN
1  2023  2.0  24.0  2.0  128.82  128.82 NaN
OK: 20230224 (24 horas)
20230225: 7 columnas
      0    1     2    3       4       5   6
0  2023  2.0  25.0  1.0  158.44  158.44 NaN
1  2023  2.0  25.0  2.0  145.30  145.30 NaN
OK: 20230225 (24 horas)
20230226: 7 columnas
      0    1     2    3      4      5   6
0  2023  2.0  26.0  1.0  136.0  136.0 NaN
1  2023  2.0  26.0  2.0  130.0  130.0 NaN
OK: 20230226 (24 horas)
20230227: 7 columnas
      0    1     2    3      4      5   6
0  2023  2.0  27.0  1.0  99.72  99.72 NaN
1  2023  2.0  27.0  2.0  97.60  97.60 NaN
OK: 20230227 (24 horas)
20230228: 7 columnas
      0    1     2    3      4      5   6
0  2023  2.0  28.0  1.0  134.0  134.0 NaN
1  2023  2.0  28.0  2.0  133.0  133.0 NaN
OK: 20230228 (24 horas)
20230301: 7 columnas
      0    1    2    3      4      5   6
0  2023  3.0  1.0  1.0  145.0  145.0 NaN
1  2023  3.0  1.0  2.0  140.0  140.0 NaN
OK: 20230301 (24 horas)
20230302: 7 columnas
      0    1    2    3       4       5   6
0  2023  3.0  2.0  1.0  145.69  145.69 NaN
1  2023  3.0  2.0  2.0  142.49  142.49 NaN
OK: 20230302 (24 horas)
20230303: 7 columnas
      0    1    2    3       4       5   6
0  2023  3.0  3.0  1.0  147.56  147.56 NaN
1  2023  3.0  3.0  2.0  145.79  145.79 NaN
OK: 20230303 (24 horas)
20230304: 7 columnas
      0    1    2    3       4       5   6
0  2023  3.0  4.0  1.0  142.24  142.24 NaN
1  2023  3.0  4.0  2.0  137.33  137.33 NaN
OK: 20230304 (24 horas)
20230305: 7 columnas
      0    1    2    3       4       5   6
0  2023  3.0  5.0  1.0  144.09  144.09 NaN
1  2023  3.0  5.0  2.0  142.00  142.00 NaN
OK: 20230305 (24 horas)
20230306: 7 columnas
      0    1    2    3       4       5   6
0  2023  3.0  6.0  1.0  149.00  149.00 NaN
1  2023  3.0  6.0  2.0  149.76  149.76 NaN
OK: 20230306 (24 horas)
20230307: 7 columnas
      0    1    2    3      4      5   6
0  2023  3.0  7.0  1.0  138.1  138.1 NaN
1  2023  3.0  7.0  2.0  133.0  133.0 NaN
OK: 20230307 (24 horas)
20230308: 7 columnas
      0    1    2    3      4      5   6
0  2023  3.0  8.0  1.0  92.10  92.10 NaN
1  2023  3.0  8.0  2.0  89.99  89.99 NaN
OK: 20230308 (24 horas)
20230309: 7 columnas
      0    1    2    3      4      5   6
0  2023  3.0  9.0  1.0  90.29  90.29 NaN
1  2023  3.0  9.0  2.0  67.69  67.69 NaN
OK: 20230309 (24 horas)
20230310: 7 columnas
      0    1     2    3      4     5   6
0  2023  3.0  10.0  1.0  30.00  30.0 NaN
1  2023  3.0  10.0  2.0  19.24  14.0 NaN
OK: 20230310 (24 horas)
20230311: 7 columnas
      0    1     2    3      4      5   6
0  2023  3.0  11.0  1.0  39.14  39.14 NaN
1  2023  3.0  11.0  2.0  33.15  33.15 NaN
OK: 20230311 (24 horas)
20230312: 7 columnas
      0    1     2    3      4      5   6
0  2023  3.0  12.0  1.0  90.00  90.00 NaN
1  2023  3.0  12.0  2.0  89.71  89.71 NaN
OK: 20230312 (24 horas)
20230313: 7 columnas
      0    1     2    3      4     5   6
0  2023  3.0  13.0  1.0  69.41  48.6 NaN
1  2023  3.0  13.0  2.0  38.10  38.1 NaN
OK: 20230313 (24 horas)
20230314: 7 columnas
      0    1     2    3     4     5   6
0  2023  3.0  14.0  1.0  9.57  9.57 NaN
1  2023  3.0  14.0  2.0  4.55  4.55 NaN
OK: 20230314 (24 horas)
20230315: 7 columnas
      0    1     2    3       4       5   6
0  2023  3.0  15.0  1.0  133.86  133.86 NaN
1  2023  3.0  15.0  2.0  124.69  124.69 NaN
OK: 20230315 (24 horas)
20230316: 7 columnas
      0    1     2    3       4       5   6
0  2023  3.0  16.0  1.0  117.39  117.39 NaN
1  2023  3.0  16.0  2.0  107.59  107.59 NaN
OK: 20230316 (24 horas)
20230317: 7 columnas
      0    1     2    3      4      5   6
0  2023  3.0  17.0  1.0  79.66  79.66 NaN
1  2023  3.0  17.0  2.0  74.57  74.57 NaN
OK: 20230317 (24 horas)
20230318: 7 columnas
      0    1     2    3       4       5   6
0  2023  3.0  18.0  1.0  111.40  111.40 NaN
1  2023  3.0  18.0  2.0  105.87  105.87 NaN
OK: 20230318 (24 horas)
20230319: 7 columnas
      0    1     2    3       4       5   6
0  2023  3.0  19.0  1.0  110.03  110.03 NaN
1  2023  3.0  19.0  2.0  106.00  106.00 NaN
OK: 20230319 (24 horas)
20230320: 7 columnas
      0    1     2    3       4       5   6
0  2023  3.0  20.0  1.0  124.00  124.00 NaN
1  2023  3.0  20.0  2.0  114.94  114.94 NaN
OK: 20230320 (24 horas)
20230321: 7 columnas
      0    1     2    3       4       5   6
0  2023  3.0  21.0  1.0  120.79  120.79 NaN
1  2023  3.0  21.0  2.0  112.28  112.28 NaN
OK: 20230321 (24 horas)
20230322: 7 columnas
      0    1     2    3      4      5   6
0  2023  3.0  22.0  1.0  109.0  109.0 NaN
1  2023  3.0  22.0  2.0  100.0  100.0 NaN
OK: 20230322 (24 horas)
20230323: 7 columnas
      0    1     2    3       4       5   6
0  2023  3.0  23.0  1.0  100.00  100.00 NaN
1  2023  3.0  23.0  2.0   87.77   87.77 NaN
OK: 20230323 (24 horas)
20230324: 7 columnas
      0    1     2    3      4      5   6
0  2023  3.0  24.0  1.0  56.74  56.74 NaN
1  2023  3.0  24.0  2.0  46.15  46.15 NaN
OK: 20230324 (24 horas)
20230325: 7 columnas
      0    1     2    3      4      5   6
0  2023  3.0  25.0  1.0  49.71  49.71 NaN
1  2023  3.0  25.0  2.0  48.92  48.92 NaN
OK: 20230325 (24 horas)
20230326: 7 columnas
      0    1     2    3     4     5   6
0  2023  3.0  26.0  1.0  45.1  45.1 NaN
1  2023  3.0  26.0  2.0  35.0  35.0 NaN
OK: 20230326 (23 horas)
20230327: 7 columnas
      0    1     2    3      4      5   6
0  2023  3.0  27.0  1.0  96.00  96.00 NaN
1  2023  3.0  27.0  2.0  94.15  94.15 NaN
OK: 20230327 (24 horas)
20230328: 7 columnas
      0    1     2    3       4       5   6
0  2023  3.0  28.0  1.0  131.77  131.77 NaN
1  2023  3.0  28.0  2.0  120.00  120.00 NaN
OK: 20230328 (24 horas)
20230329: 7 columnas
      0    1     2    3      4      5   6
0  2023  3.0  29.0  1.0  98.53  98.53 NaN
1  2023  3.0  29.0  2.0  91.99  91.99 NaN
OK: 20230329 (24 horas)
20230330: 7 columnas
      0    1     2    3     4      5   6
0  2023  3.0  30.0  1.0  35.0  35.00 NaN
1  2023  3.0  30.0  2.0  40.0  33.01 NaN
OK: 20230330 (24 horas)
20230331: 7 columnas
      0    1     2    3      4      5   6
0  2023  3.0  31.0  1.0  27.83  27.83 NaN
1  2023  3.0  31.0  2.0  19.90  19.90 NaN
OK: 20230331 (24 horas)
20230401: 7 columnas
      0    1    2    3      4      5   6
0  2023  4.0  1.0  1.0  82.19  82.19 NaN
1  2023  4.0  1.0  2.0  63.90  63.90 NaN
OK: 20230401 (24 horas)
20230402: 7 columnas
      0    1    2    3     4     5   6
0  2023  4.0  2.0  1.0  19.0  19.0 NaN
1  2023  4.0  2.0  2.0  18.6  18.6 NaN
OK: 20230402 (24 horas)
20230403: 7 columnas
      0    1    2    3      4      5   6
0  2023  4.0  3.0  1.0  52.62  52.62 NaN
1  2023  4.0  3.0  2.0  48.43  48.43 NaN
OK: 20230403 (24 horas)
20230404: 7 columnas
      0    1    2    3      4      5   6
0  2023  4.0  4.0  1.0  92.18  92.18 NaN
1  2023  4.0  4.0  2.0  68.25  68.25 NaN
OK: 20230404 (24 horas)
20230405: 7 columnas
      0    1    2    3       4       5   6
0  2023  4.0  5.0  1.0   70.25   70.25 NaN
1  2023  4.0  5.0  2.0  108.76  108.76 NaN
OK: 20230405 (24 horas)
20230406: 7 columnas
      0    1    2    3       4       5   6
0  2023  4.0  6.0  1.0  135.54  135.54 NaN
1  2023  4.0  6.0  2.0  124.12  124.12 NaN
OK: 20230406 (24 horas)
20230407: 7 columnas
      0    1    2    3       4       5   6
0  2023  4.0  7.0  1.0  116.61  116.61 NaN
1  2023  4.0  7.0  2.0  110.43  110.43 NaN
OK: 20230407 (24 horas)
20230408: 7 columnas
      0    1    2    3       4       5   6
0  2023  4.0  8.0  1.0  126.24  126.24 NaN
1  2023  4.0  8.0  2.0  115.07  115.07 NaN
OK: 20230408 (24 horas)
20230409: 7 columnas
      0    1    2    3       4       5   6
0  2023  4.0  9.0  1.0  127.99  127.99 NaN
1  2023  4.0  9.0  2.0  117.86  117.86 NaN
OK: 20230409 (24 horas)
20230410: 7 columnas
      0    1     2    3      4      5   6
0  2023  4.0  10.0  1.0  98.21  98.21 NaN
1  2023  4.0  10.0  2.0  81.85  81.85 NaN
OK: 20230410 (24 horas)
20230411: 7 columnas
      0    1     2    3      4      5   6
0  2023  4.0  11.0  1.0  68.50  68.50 NaN
1  2023  4.0  11.0  2.0  68.14  68.14 NaN
OK: 20230411 (24 horas)
20230412: 7 columnas
      0    1     2    3      4      5   6
0  2023  4.0  12.0  1.0  93.65  93.65 NaN
1  2023  4.0  12.0  2.0  65.74  65.74 NaN
OK: 20230412 (24 horas)
20230413: 7 columnas
      0    1     2    3      4      5   6
0  2023  4.0  13.0  1.0  79.41  79.41 NaN
1  2023  4.0  13.0  2.0  74.10  74.10 NaN
OK: 20230413 (24 horas)
20230414: 7 columnas
      0    1     2    3      4      5   6
0  2023  4.0  14.0  1.0  90.76  90.76 NaN
1  2023  4.0  14.0  2.0  87.72  87.72 NaN
OK: 20230414 (24 horas)
20230415: 7 columnas
      0    1     2    3      4      5   6
0  2023  4.0  15.0  1.0  36.38  36.38 NaN
1  2023  4.0  15.0  2.0  34.90  34.90 NaN
OK: 20230415 (24 horas)
20230416: 7 columnas
      0    1     2    3      4      5   6
0  2023  4.0  16.0  1.0  28.28  28.28 NaN
1  2023  4.0  16.0  2.0  26.10  26.10 NaN
OK: 20230416 (24 horas)
20230417: 7 columnas
      0    1     2    3      4      5   6
0  2023  4.0  17.0  1.0  86.03  86.03 NaN
1  2023  4.0  17.0  2.0  81.87  81.87 NaN
OK: 20230417 (24 horas)
20230418: 7 columnas
      0    1     2    3       4       5   6
0  2023  4.0  18.0  1.0  105.31  105.31 NaN
1  2023  4.0  18.0  2.0   81.99   81.99 NaN
OK: 20230418 (24 horas)
20230419: 7 columnas
      0    1     2    3       4       5   6
0  2023  4.0  19.0  1.0  127.54  127.54 NaN
1  2023  4.0  19.0  2.0  116.80  116.80 NaN
OK: 20230419 (24 horas)
20230420: 7 columnas
      0    1     2    3       4       5   6
0  2023  4.0  20.0  1.0  126.00  126.00 NaN
1  2023  4.0  20.0  2.0  122.03  122.03 NaN
OK: 20230420 (24 horas)
20230421: 7 columnas
      0    1     2    3       4       5   6
0  2023  4.0  21.0  1.0  122.50  122.50 NaN
1  2023  4.0  21.0  2.0  112.39  112.39 NaN
OK: 20230421 (24 horas)
20230422: 7 columnas
      0    1     2    3       4       5   6
0  2023  4.0  22.0  1.0  122.01  122.01 NaN
1  2023  4.0  22.0  2.0  101.95  101.95 NaN
OK: 20230422 (24 horas)
20230423: 7 columnas
      0    1     2    3       4       5   6
0  2023  4.0  23.0  1.0  108.00  108.00 NaN
1  2023  4.0  23.0  2.0   97.52   97.52 NaN
OK: 20230423 (24 horas)
20230424: 7 columnas
      0    1     2    3     4     5   6
0  2023  4.0  24.0  1.0  90.0  90.0 NaN
1  2023  4.0  24.0  2.0  91.8  91.8 NaN
OK: 20230424 (24 horas)
20230425: 7 columnas
      0    1     2    3       4       5   6
0  2023  4.0  25.0  1.0  127.39  127.39 NaN
1  2023  4.0  25.0  2.0  123.56  123.56 NaN
OK: 20230425 (24 horas)
20230426: 7 columnas
      0    1     2    3       4       5   6
0  2023  4.0  26.0  1.0  106.79  106.79 NaN
1  2023  4.0  26.0  2.0   99.91   99.91 NaN
OK: 20230426 (24 horas)
20230427: 7 columnas
      0    1     2    3       4       5   6

In [22]:
df.shape

(8736, 7)

In [23]:
df.columns

Index(['year', 'month', 'day', 'hour', 'price_es', 'price_pt', 'datetime'], dtype='object')

# Let´s introduce SQLite

In [24]:
import sqlite3

# Crear base de datos SQLite
base_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
db_path = os.path.join(base_dir, "data", "electricity.db")
conn = sqlite3.connect(db_path)

# Guardar el dataframe en SQLite
df.to_sql("omie_prices", conn, if_exists="replace", index=False)
print(f"Tabla creada con {len(df)} filas")

# Verificar con una query SQL
result = pd.read_sql("SELECT COUNT(*) as total FROM omie_prices", conn)
print(result)

conn.close()

Tabla creada con 8736 filas
   total
0   8736

In [25]:
conn = sqlite3.connect(db_path)

# Precio medio por hora del día
pd.read_sql("""
    SELECT hour, AVG(price_es) as avg_price
    FROM omie_prices
    GROUP BY hour
    ORDER BY hour
""", conn)

    hour   avg_price
0    1.0   94.615934
1    2.0   87.648049
2    3.0   83.385165
3    4.0   81.098242
4    5.0   79.531264
5    6.0   82.528352
6    7.0   91.126016
7    8.0  101.341429
8    9.0  103.926374
9   10.0   93.321291
10  11.0   80.308626
11  12.0   74.506758
12  13.0   71.624945
13  14.0   69.045934
14  15.0   65.790632
15  16.0   64.714093
16  17.0   68.561236
17  18.0   78.948516
18  19.0   91.596319
19  20.0  107.635137
20  21.0  119.544698
21  22.0  118.265714
22  23.0  109.680934
23  24.0  100.166336
24  25.0   27.000000

In [26]:
# Los 10 días con precio más alto
pd.read_sql("""
    SELECT year, month, day, AVG(price_es) as avg_price
    FROM omie_prices
    GROUP BY year, month, day
    ORDER BY avg_price DESC
    LIMIT 10
""", conn)

   year  month   day   avg_price
0  2023    2.0  21.0  151.427083
1  2023    2.0  24.0  148.078750
2  2023    3.0   6.0  147.770833
3  2023    2.0  13.0  146.767083
4  2023    3.0   1.0  145.911250
5  2023    2.0  16.0  145.327500
6  2023    2.0  15.0  145.070833
7  2023    2.0   9.0  144.996250
8  2023    2.0  22.0  144.449583
9  2023    3.0   5.0  143.924167

In [27]:
# Precio medio por mes
pd.read_sql("""
    SELECT month, AVG(price_es) as avg_price
    FROM omie_prices
    GROUP BY month
    ORDER BY month
""", conn)

#conn.close()

    month   avg_price
0     1.0   69.347554
1     2.0  134.230491
2     3.0   90.045989
3     4.0   76.959292
4     5.0   75.791208
5     6.0   95.586694
6     7.0   93.799879
7     8.0   97.859167
8     9.0  104.147694
9    10.0   89.744899
10   11.0   63.258097
11   12.0   72.204207